name: Send Dynamic Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Recipient Email"
        required: true
      username:
        description: "User Name"
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug File Structure  # ✅ Check if package.json exists
        run: |
          pwd
          ls -R

      - name: Install Dependencies  # ✅ Only run if package.json exists
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "⚠️ No package.json found. Skipping npm install."
          fi

      - name: Run Email Script
        run: node sendEmail.js
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ github.event.inputs.email }}
          USERNAME: ${{ github.event.inputs.username }}
          OTHER : ${{ github.event.inputs }}
