name: Send Dynamic Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Recipient Email"
        required: true
      username:
        description: "User Name"
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository  # ✅ Ensures the repo files are available
        uses: actions/checkout@v3

      - name: Debug File Structure  # ✅ Check if package.json exists
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies  # ✅ If package.json is inside a subfolder, modify the path
        run: npm install
        working-directory: .  # Change this if your package.json is inside a subfolder (e.g., backend)

      - name: Run Email Script
        run: node sendEmail.js
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ github.event.inputs.email }}
          USERNAME: ${{ github.event.inputs.username }}
