name: Send Dynamic Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Recipient Email"
        required: true
      username:
        description: "User Name"
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Email Script
        run: node sendEmail.js
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ github.event.inputs.email }}
          USERNAME: ${{ github.event.inputs.username }}
